name: Flawfinder Security Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  flawfinder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Flawfinder
        run: |
          python -m pip install --upgrade pip
          pip install flawfinder
          
      - name: Run Flawfinder
        run: |
          flawfinder --html --context --minlevel=3 . > flawfinder_report.html

      - name: Check for high-risk vulnerabilities (level 5)
        run: |
          flawfinder . > flawfinder_raw.txt
          cat flawfinder_raw.txt
          level5_hits=$(grep -oP '\[5\]\s+\K\d+' flawfinder_raw.txt | head -1)
          echo "Level 5 hits: $level5_hits"
          if [ "$level5_hits" -gt 0 ]; then
            echo "❌ Level 5 vulnerabilities detected! Failing build."; exit 1;
          else
            echo "✅ No level 5 vulnerabilities found.";
          fi

      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: flawfinder-report
          path: flawfinder_report.html
